# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'faraday', '~> 1.7.1'
gem 'faraday_middleware', '~> 1.1.0'
gem 'hamlit', '~> 2.15.1'
gem 'monetize'
gem 'sinatra', '~> 2.1'
gem 'sinatra-reloader', '~> 1.0'
